// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoJOHAHdVZxv-Trvwa6HerPNC_Rh8LjzE',
    appId: '1:293012500791:web:624983d37008e963b8aab2',
    messagingSenderId: '293012500791',
    projectId: 'lab-manager-fb25b',
    authDomain: 'lab-manager-fb25b.firebaseapp.com',
    storageBucket: 'lab-manager-fb25b.firebasestorage.app',
    measurementId: 'G-VRSR9EDJHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtBpGg4sPMVgsWcjSPX01wHDR-O1eWZZ0',
    appId: '1:293012500791:android:7e8f59124a19b24ab8aab2',
    messagingSenderId: '293012500791',
    projectId: 'lab-manager-fb25b',
    storageBucket: 'lab-manager-fb25b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXCgOzq309-rbMBt7Ye4DZI6Rod6AP6I',
    appId: '1:293012500791:ios:7482949d4a095c10b8aab2',
    messagingSenderId: '293012500791',
    projectId: 'lab-manager-fb25b',
    storageBucket: 'lab-manager-fb25b.firebasestorage.app',
    iosBundleId: 'com.example.labManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXCgOzq309-rbMBt7Ye4DZI6Rod6AP6I',
    appId: '1:293012500791:ios:7482949d4a095c10b8aab2',
    messagingSenderId: '293012500791',
    projectId: 'lab-manager-fb25b',
    storageBucket: 'lab-manager-fb25b.firebasestorage.app',
    iosBundleId: 'com.example.labManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoJOHAHdVZxv-Trvwa6HerPNC_Rh8LjzE',
    appId: '1:293012500791:web:a4edece7982ec17eb8aab2',
    messagingSenderId: '293012500791',
    projectId: 'lab-manager-fb25b',
    authDomain: 'lab-manager-fb25b.firebaseapp.com',
    storageBucket: 'lab-manager-fb25b.firebasestorage.app',
    measurementId: 'G-3LBHQ3TR9E',
  );
}
